networks:
  proxy:
    external: true

services:
  # override older
  playwright-service:
    restart: on-failure:3
    environment:
      - BLOCK_MEDIA=true # drop images/video/fonts at network level
      - MAX_CONCURRENT_PAGES=2
    networks:
      proxy:
        aliases:
          - firecrawl-playwright-service

  api:
    restart: on-failure:3
    ports: !override []
    environment:
      - NUM_WORKERS_PER_QUEUE=2
      - CRAWL_CONCURRENT_REQUESTS=2
      - MAX_CONCURRENT_JOBS=2
      - BROWSER_POOL_SIZE=2
    networks:
      proxy:
        aliases:
          - firecrawl-api
  
  redis:
    restart: on-failure:3
    networks:
      proxy:
        aliases:
          - firecrawl-redis

  rabbitmq:
    restart: on-failure:3
    networks:
      proxy:
        aliases:
          - firecrawl-rabbitmq

  nuq-postgres:
    restart: on-failure:3
    networks:
      proxy:
        aliases:
          - firecrawl-nuq-postgres