global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: stremio_albanian_subs_addon
    static_configs:
      - targets:
          - stremio_albanian_subs_addon:8000

  - job_name: cadvisor
    static_configs:
      - targets:
          - "cadvisor:8080"
