volumes:
  portainer_data:
    name: portainer_data

networks:
  proxy:
    name: proxy
    driver: bridge

services:
  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - proxy

  portainer:
    image: portainer/portainer-ce:2.40.0
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "wget",
    #       "--no-verbose",
    #       "--tries=1",
    #       "--spider",
    #       "http://localhost:9000",
    #     ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
