networks:
  proxy:
    external: true

services:
  p2p_video_chat_backend:
    image: ghcr.io/xhuliodo/p2p_video_chat_backend:latest
    container_name: p2p_video_chat_backend
    restart: on-failure:3
    environment:
      - CLOUDFLARE_TURN_TOKEN_ID=${CLOUDFLARE_TURN_TOKEN_ID}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    networks:
      - proxy
    labels:
      - wud.watch=true
      - wud.watch.digest=true
      - wud.trigger.include=docker.latest,discord.deployments