networks:
  proxy:
    external: true

services:
  p2p_video_chat_backend:
    image: ghcr.io/xhuliodo/p2p_video_chat_backend:latest
    container_name: p2p_video_chat_backend
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - wud.watch=true
      - wud.watch.digest=true
      - wud.trigger.include=docker.latest,discord.deployments