networks:
  proxy:
    external: true

volumes:
  open_webui:
    name: open_webui
  searxng_data:
    name: searxng_data
  searxng_cache:
    name: searxng_cache

services:
  open_webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui
    restart: on-failure:3
    volumes:
      - open_webui:/app/backend/data
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    networks:
      - proxy
    labels:
      - wud.watch=true
      - wud.watch.digest=true
      - wud.trigger.include=docker.latest,discord.deployments
  searxng:
    image: ghcr.io/searxng/searxng:latest
    container_name: searxng
    restart: on-failure:3
    networks:
      - proxy
    volumes:
      - searxng_data:/etc/searxng
      - searxng_cache:/var/cache/searxng/
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET_KEY}
      - SEARXNG_BASE_URL=http://searxng:8080/
    labels:
      - wud.watch=true
      - wud.watch.digest=true
      - wud.trigger.include=docker.latest,discord.deployments