volumes:
  searxng_data:
    name: searxng_data
  searxng_cache:
    name: searxng_cache

networks:
  proxy:
    external: true

services:

  # new services
  searxng:
    image: ghcr.io/searxng/searxng:latest
    container_name: searxng
    restart: on-failure:3
    networks:
      - proxy
    volumes:
      - searxng_data:/etc/searxng
      - searxng_cache:/var/cache/searxng/
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET_KEY}
      - SEARXNG_BASE_URL=${SEARXNG_INSTANCE_URL}

  # override older
  api:
    image: registry.librechat.ai/danny-avila/librechat:latest
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: /app/librechat.yaml
    ports: []
    restart: on-failure:3
    networks:
      - proxy
  
  mongodb:
    restart: on-failure:3
    networks:
      - proxy

  meilisearch:
    restart: on-failure:3
    networks:
      - proxy

  vectordb:
    restart: on-failure:3
    networks:
      - proxy

  rag_api:
    restart: on-failure:3
    networks:
      - proxy

